owner = "lozik"

[paths.output]

[paths.input]

[apis.Kroger.prod]
url = "https://api.kroger.com/v1/"
auth_url = "https://api.kroger.com/v1/connect/oauth2/authorize"
token_url = "https://api.kroger.com/v1/connect/oauth2/token"

[paths.private_keys.prod]
path = "/home/lozik/code/snippets/python/login_setup/prod_key.json"

[paths.private_keys.stage]
path = "/home/lozik/code/snippets/python/login_setup/stage_key.json"

[paths.private_keys.dev]
path = "/home/lozik/code/snippets/python/login_setup/dev_key.json"

[servers.SqlServer1.prod]
address = "localhost"
database = "AdventureWorks2021"
username = "gAAAAABhz13qyiTKiKecvCfFCDdj3OZC-EpXQvj0FanR0qJncg3Istw-476kvlLE2u4yQ0DQHRKeeCeKRo_WhRntNNCeI7MA1g=="
password = "gAAAAABhz13qjt4Ivv7hQHIhXe1MvGIoiISAB4W0WNmvJ0pwmwN7WSK0PLf6X0RNRUhTQG4JZPjIdy_v8Rt0CJTHsmy9yvVPoDa8XFp8e6l6XeszPKWy6SA="

[apis.Kroger.prod.auth_creds]
client_id = "gAAAAABhz138jkP9RX0ZTs2h-lfnrtxRt3mPOxONGZtXwzfqcV3jwQLnf5a9Gh9PB_dden9UOjb0FO5TTEU_uFH44mqu0Ga8xQ=="
client_secret = "gAAAAABhz138m9ffS36kImQGEL43_6GLli6Q0xTPoOX0O1Ti-VDVzkkavIwb6L_XgAp8xX9jJIQx83KRvzzKDtB5tZJluHQ9fQ=="
