owner = "lozik"

[paths.output]

[paths.input]

[paths.private_keys.prod]
path = "/home/lozik/.auth/prod_key.json"

[paths.private_keys.stage]
path = "/home/lozik/.auth/stage_key.json"

[paths.private_keys.dev]
path = "/home/lozik/.auth/dev_key.json"

[apis.Kroger.prod]
url = "https://api.kroger.com/v1/"
auth_url = "https://api.kroger.com/v1/connect/oauth2/authorize"
token_url = "https://api.kroger.com/v1/connect/oauth2/token"

[servers.SqlServer1.prod]
address = "localhost"
database = "AdventureWorks2021"
username = "gAAAAABh0pILq1JSOWvcCuEapDJK68_cYBuhCdo6KRLNZkPF9plLyV4JsbDq1IL8gsfXKW8rQ_i0Hcw551TVCpBYZhiQXP0lng=="
password = "gAAAAABh0pIL0k05KRh2WuWQ2NmBM2ygPu1AczIg1U1gtgqsFGe3LqD7dKh4bF0amXRQr-qE4AijFnQtfh4aKYl6XH9Z8VHdnWT-pVO4y9ZntfzOjeRU43M="

[servers.SqlServer1.stage]
address = "localhost"
database = "AdventureWorks2021"
username = "gAAAAABh0pILmBeGtq1aJT1zyd06Z5zyzIwaMN2ChbLKZMVPP8ZOOenqaAiVYD3W-70dxu9jCPHKYrN9MlksVdeZEPYRqN2j2A=="
password = "gAAAAABh0pILKcO430DizgLlWOTPhCggcsWHNx37zqmV6f2_OuDfaZjycTbkgvPHLm7a51kAuUyVx7OcB-txZ1gbfc7u_b2hJA=="

[servers.SqlServer1.dev]
address = "localhost"
database = "AdventureWorks2021"
username = "gAAAAABh0pILnHGr3lSLZq3EIQ3fCUbddB4pCkH3KJms0t-QoPuoN8HM3dYWhQmSJyjn-xwm_4dyghbxSjo-tsMeH4UlHb1A8Q=="
password = "gAAAAABh0pILcsheqTq_cLequQmowykCj_96Q22LvwJt92YnPkC1xGRVujMAur6Pfs4t5cXAMi0C2ZVYgUIZpN7-sqiMmlmxvw=="

[apis.Kroger.prod.auth_creds]
client_id = "gAAAAABh0pILhtcl3sj4W1J8bFv6z31Dx5ZO-QS0U1IlLiNvnX5NALr6sMiJj7un4ebxH8Qp51nWTpK408_dXhXJhfG2dv7IKJraWjYI60CrpysWJJYX8nU="
client_secret = "gAAAAABh0pILpwCQFgZzUDUojcNdLzBRzNJK7NECi5sxyhhPkJ7Xe9uUpKrHn4y_q2KKVd2kW69O2EU9gdS2rISJmXomAIHujI5gSy9LiXWsTY8ucGGUXkc="
