owner = "lozik"

[paths.output]

[paths.input]

[paths.private_keys.prod]
path = "/home/lozik/.auth/prod_key.json"

[paths.private_keys.stage]
path = "/home/lozik/.auth/stage_key.json"

[paths.private_keys.dev]
path = "/home/lozik/.auth/dev_key.json"

[apis.Kroger.prod]
url = "https://api.kroger.com/v1/"
auth_url = "https://api.kroger.com/v1/connect/oauth2/authorize"
token_url = "https://api.kroger.com/v1/connect/oauth2/token"

[databases.SqlServer1.prod]
address = "localhost"
database = "AdventureWorks2021"
username = "gAAAAABh0yoU8qcCfMBmAKb4VkPtAIRGB9DtGQ-0i7quRHxn3V8OIeB0i-Ab3v-hLIhc16SXN-Ey7oRGJZcs9hUrvK2-EBYFSg=="
password = "gAAAAABh0yoUyDkysVVmMuEX3fVPvfWeBKuUVnGWCyjc228cd8iULUKxi67XiThWyAjIXCNIvifHEINw-30Bypp5wFhhwbuxKiSa6Hl7K0p5RsnBKlP3JCE="

[databases.SqlServer1.stage]
address = "localhost"
database = "AdventureWorks2021"
username = "gAAAAABh0yoU_KCmAuQAZlpITfGkBb0UjzpU-jo5rzbzmstLM2auyAwLOgbMQEcPFiNjpg9e7zIIUEi44cptxH_p3wGHIWoOIA=="
password = "gAAAAABh0yoUnXibtgrlY9N1QcVX7hhMODExnB_q467F1bmqhHXC-cn1yliztwFMWb3yLuaIdrZzX5_AFKyY1Y5_3VTOfAwWCw=="

[databases.SqlServer1.dev]
address = "localhost"
database = "AdventureWorks2021"
username = "gAAAAABh0yoUwBtHrsJ72En2v--TtwgrMXDyCZR5bfJEyYJueF3Gw4nwt3KfgzvC076GJ9CPXzw373Pm-s3zl7SquUJHQp6dug=="
password = "gAAAAABh0yoUdS5PTGIKiEwBAgEFf6sI5cparjWNTz-rATFOx-g0EgqqrkUAfoXhbRXYmA_-6eRxi9uRVB8cOX0sgBJ-uJ1SLg=="

[apis.Kroger.prod.auth_creds]
client_id = "gAAAAABh0yoU_4girroiorY5j8lKnF3EZWmDbqIjwKvro0-JjF_EQ3N2CHASMUqhW7GY05o6yhO2aiuuuRwnpPMeRbVTF2bGFANfSOZazfToUkArbBmI8Ys="
client_secret = "gAAAAABh0yoUg_O8cbGuigHXQuNq-qYKi82x3mqPv85uLARwl3BURqiL4KBjQvAeVAETMZbqIwDse63Z2CsZXVieNlBwR720WYCf8AIqoOvAcwrKyP8Yy1E="
