owner = "lozik"

[paths.output]

[paths.input]

[paths.private_keys.prod]
path = "/home/lozik/code/snippets/python/login_setup/prod_key.json"

[paths.private_keys.stage]
path = "/home/lozik/code/snippets/python/login_setup/stage_key.json"

[paths.private_keys.dev]
path = "/home/lozik/code/snippets/python/login_setup/dev_key.json"

[servers.SqlServer1.prod]
address = "localhost"
database = "AdventureWorks2021"
username = "gAAAAABhzNy7kbXMIIAqt3O0mAtfWRL7-UjAyDPqS5_oGWMRr38MJmjECjC6W5eTo2_CxupXgEG-sJIjqcTQySKrB8TE-k2tDw=="
password = "gAAAAABhzNy7vnIsEo6sI1PpZP81ARnFk_3pwBA82S0xhkktJiBlhz02Zt0BAGjjVWzi5-Eewm2G7of21IYbpHI7gkmQIXSBHg=="

[servers.SqlServer1.dev]
address = "localhost"
database = "AdventureWorks2021"
username = "gAAAAABhzNy7gDeLw0LQW9Aa_zKUH6alFvS0pxGGd_woqOVM_qqBNshHg9Ln5h1T9ZzVx7il088qM4Hr3oDH-BfHZFfHfkeMzg=="
password = "gAAAAABhzNy7lrXygEFAlYoKN-9FqLurOjFIx8IGb2XVyYNEKu6f0EUphXwGsF8WbZf3vowepcjsC_EgueTE0t56LKicSA9KmQ=="

[servers.SqlServer1.stage]
address = "localhost"
database = "AdventureWorks2021"
username = "gAAAAABhzNy777l-KrHDW6ns4FV94s1tf05EF5TjK_FK_xRLdO5cI2m-HnaqGqg5WaJCbqEIx7Gq2EhL6vYUxcYN5cvUdoZebg=="
password = "gAAAAABhzNy7iPWRx3YazQidbHfeib3wXRA8gjgW3GaBTLDQ-tT-HCG4fgoqVL3AcAdY9IRJPB6e2_zGvng7hyn23lNfa9w8OQ=="

[servers.SqlServer2.prod]
address = "c192.al"
database = "okok"
username = "gAAAAABhzNy7y9cqWjlKtRvgynvVvwtcK5EQKky79PKy5nKvEYR1vItaiz-91R6CB7Kq-Hxgnw3eOotZG_NTS-q0vNegLATSIg=="
password = "gAAAAABhzNy7n0xwhibEIR5tqiCC4duTYS2JQYXfXLNDuo74bOJLkqw60F-a0j6EErVFju6KN8Zh9F5XR1zs615_u99Rm31_sA=="

[servers.SqlServer2.dev]
address = "localhost"
database = "AdventureWorks2021"
username = "gAAAAABhzNy7GTX9wF2VHvFPnQBnBn931AxVgWXm2R-HwGFQDmK7QEQzp07WImpt40NdRZPtxrL31CLzZDV6ItlzaOtIFQTsnQ=="
password = "gAAAAABhzNy7m3ErMBOxupEWAb-TrKWezl5U4DxH31LBdxM0lZ4oJvNJVuvGtHBNFQvbW26V1LhNm4SYU_1-wjFOD4Xqr4dqsw=="

[servers.SqlServer2.stage]
address = "localhost"
database = "AdventureWorks2021"
username = "gAAAAABhzNy7YKgbA4ggLBvmcmrqiTS8v2nBuV25j1c4B1dEKG-M7i2pfDRHFxobg7VtaG4UivK0Oe8B8JO5-zeuoBx-uv_hLw=="
password = "gAAAAABhzNy7mvZ-YM_9ZPG3ySzrfM8tqIBN7lBh6sYrwTqDQC_9VPdthfN3bl5j27x3qr5r8fV9hsdH16mRZapKWfiLmzbMsg=="
